name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up V
        uses: vlang/setup-v@v1.4
      - name: Cache V modules
        uses: actions/cache@v3
        with:
          path: ~/.vmodules
          key: ${{ runner.os }}-vmodules-${{ hashFiles('**/v.mod') }}
          restore-keys: |
            ${{ runner.os }}-vmodules-

      - name: Run all tests
        run: |
          v test .
          v test examples/simple/src
          v test examples/simple2/src
          v test examples/etag/src
