name: Pretty Fmt Checker

on:
  pull_request:
    branches: [ main ]

jobs:
  fmt-check:
    name: v fmt -verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up V
        uses: vlang/setup-v@v1.4
      - name: Remove Vlang folder to avoid conflicts
        shell: bash
        run: |
          rm -rf -v ./vlang || true
      - name: Run v fmt checker
        shell: bash
        run: |
          v fmt -verify .
