name: Pretty Fmt Checker

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  fmt-check:
    name: v fmt -verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up V
        uses: vlang/setup-v@v1.4
      - name: Run v fmt check
        shell: bash
        run: |
            for file in $(find . -type f \( -name '*.v' -o -name '*.vv' \)); do \
                v fmt -verify "$file" \
            done
